server:
  port: 8090
  ssl:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
