server:
  port: 8090
  ssl:
    enabled: false
spring:
  application:
    name: webflux-client
  data:
    redis:
      host: 172.16.12.219
      port: 6379
      password: 123456
      database: 0
      connect-timeout: 3000ms
      lettuce:
        pool:
          enabled: true
          max-active: 20 #连接池最大连接数（使用负值表示没有限制）,默认20
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）,默认-1
          max-idle: 8 # 连接池中的最大空闲连接,默认8
          min-idle: 0 # 连接池中的最小空闲连接,默认0
  #  session:
  #    redis:
  #      flush-mode: on_save
  #      namespace: spring:session
  #    timeout: 1800s
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: auth-server
            client-id: gateway-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
        provider:
          auth-server:
            issuer-uri: http://localhost:9000
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.reactive: TRACE
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.core: TRACE