spring:
  mail:
    host: 172.16.12.219
    port: 1025
    username: adminUser
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
      enabled: true
      exclude: /cc/realtec/real/auth/server/domain/converter/**